apiVersion: v1
kind: Service
metadata:
  name: ingress-ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31434
    - name: https
      port: 443
      targetPort: https
      nodePort: 32216
    - name: health
      port: 10254 
      targetPort: health
      nodePort: 31000
    - name: metrics
      port: 10254 
      targetPort: metrics
      nodePort: 31001
    - name: webhook
      port: 8443  
      targetPort: webhook
      nodePort: 31002 


