apiVersion: v1
kind: Secret
metadata:
  name: prodental-secrets
  namespace: prodental
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wdw==        # root_pw
  MYSQL_DATABASE: cHJvZGVudGFs              # prodental
  MYSQL_USER: cHJvZGVudGFs                  # prodental
  MYSQL_PASSWORD: cHJvZGVudGFsX3B3          # prodental_pw
