apiVersion: v1   # API version for Kubernetes objects
kind: PersistentVolumeClaim # Type of Kubernetes object
metadata: 
  name: mysql-pvc # Name of the PersistentVolumeClaim
  namespace: prodental # Namespace where the PVC will be created
spec:
  accessModes:  
    - ReadWriteOnce # Access mode for the PVC
  resources: # Resource requirements for the PVC
    requests:  # Resource requests for the PVC
      storage: 5Gi # Amount of storage requested for the PVC
