apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    release: mon
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - prodental
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
